
import { pgTable, text, serial, integer, boolean, timestamp, jsonb, real } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const analyses = pgTable("analyses", {
  id: serial("id").primaryKey(),
  filename: text("filename").notNull(),
  micType: text("mic_type").notNull(), // dynamic, ribbon, condenser
  micPosition: text("mic_position").notNull(), // center, edge, off-axis
  speakerModel: text("speaker_model").notNull(),
  distance: text("distance").notNull(), // close, 1 inch, 6 inches, etc
  genre: text("genre").notNull().default("classic-rock"), // target genre for context-aware advice
  
  // Technical metrics
  durationSamples: integer("duration_samples").notNull(),
  peakAmplitudeDb: real("peak_amplitude_db").notNull(),
  spectralCentroid: real("spectral_centroid").notNull(), // brightness
  
  // AI Results
  advice: text("advice").notNull(),
  qualityScore: integer("quality_score").notNull(), // 0-100
  isPerfect: boolean("is_perfect").default(false),
  
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAnalysisSchema = createInsertSchema(analyses).omit({ 
  id: true, 
  createdAt: true,
  advice: true,       // Generated by backend
  qualityScore: true, // Generated by backend
  isPerfect: true     // Generated by backend
});

// Input type for the API (includes audio metrics calculated by client)
export const analysisRequestSchema = insertAnalysisSchema.extend({
  lowEnergy: z.number().min(0).max(1),
  midEnergy: z.number().min(0).max(1),
  highEnergy: z.number().min(0).max(1),
  subBassEnergy: z.number().optional(),
  bassEnergy: z.number().optional(),
  lowMidEnergy: z.number().optional(),
  midEnergy6: z.number().optional(),
  highMidEnergy: z.number().optional(),
  presenceEnergy: z.number().optional(),
  ultraHighEnergy: z.number().optional(),
  frequencySmoothness: z.number().optional(),
  noiseFloorDb: z.number().optional(),
  originalFilename: z.string().optional(),
  spectralTilt: z.number().optional(),
  rolloffFreq: z.number().optional(),
  smoothScore: z.number().optional(),
  maxNotchDepth: z.number().optional(),
  notchCount: z.number().optional(),
  logBandEnergies: z.array(z.number()).optional(),
  tailLevelDb: z.number().nullable().optional(),
  tailStatus: z.string().optional(),
});

export type Analysis = typeof analyses.$inferSelect;
export type InsertAnalysis = z.infer<typeof insertAnalysisSchema>;
export type AnalysisRequest = z.infer<typeof analysisRequestSchema>;

export const preferenceSignals = pgTable("preference_signals", {
  id: serial("id").primaryKey(),
  action: text("action").notNull(), // "love", "like", "meh", "nope", "ratio_pick"
  feedback: text("feedback"), // optional tonal feedback tags, comma-separated e.g. "thin,harsh" or single "muddy"
  feedbackText: text("feedback_text"), // optional free-form text feedback for nuanced learning
  baseFilename: text("base_filename").notNull(),
  featureFilename: text("feature_filename").notNull(),
  subBass: real("sub_bass").notNull(),
  bass: real("bass").notNull(),
  lowMid: real("low_mid").notNull(),
  mid: real("mid").notNull(),
  highMid: real("high_mid").notNull(),
  presence: real("presence").notNull(),
  ratio: real("ratio").notNull(),
  score: integer("score").notNull(),
  profileMatch: text("profile_match").notNull(), // "Featured", "Body"
  blendRatio: real("blend_ratio"), // base portion of the blend (0.3-0.7), null means 50:50
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertPreferenceSignalSchema = createInsertSchema(preferenceSignals).omit({
  id: true,
  createdAt: true,
});

export type PreferenceSignal = typeof preferenceSignals.$inferSelect;
export type InsertPreferenceSignal = z.infer<typeof insertPreferenceSignalSchema>;

export const tonalProfiles = pgTable("tonal_profiles", {
  id: serial("id").primaryKey(),
  mic: text("mic").notNull(),
  position: text("position").notNull(),
  distance: text("distance").notNull(),
  speaker: text("speaker").notNull(),
  subBass: real("sub_bass").notNull(),
  bass: real("bass").notNull(),
  lowMid: real("low_mid").notNull(),
  mid: real("mid").notNull(),
  highMid: real("high_mid").notNull(),
  presence: real("presence").notNull(),
  ratio: real("ratio").notNull(),
  centroid: real("centroid").notNull(),
  smoothness: real("smoothness").notNull(),
  sampleCount: integer("sample_count").notNull().default(1),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertTonalProfileSchema = createInsertSchema(tonalProfiles).omit({
  id: true,
  updatedAt: true,
});

export type TonalProfile = typeof tonalProfiles.$inferSelect;
export type InsertTonalProfile = z.infer<typeof insertTonalProfileSchema>;

export const customMods = pgTable("custom_mods", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  appliesTo: text("applies_to").array().notNull(),
  description: text("description").notNull(),
  resultJson: jsonb("result_json").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertCustomModSchema = createInsertSchema(customMods).omit({
  id: true,
  createdAt: true,
});

export type CustomMod = typeof customMods.$inferSelect;
export type InsertCustomMod = z.infer<typeof insertCustomModSchema>;
