
import { pgTable, text, serial, integer, boolean, timestamp, jsonb, real } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const analyses = pgTable("analyses", {
  id: serial("id").primaryKey(),
  filename: text("filename").notNull(),
  micType: text("mic_type").notNull(), // dynamic, ribbon, condenser
  micPosition: text("mic_position").notNull(), // center, edge, off-axis
  distance: text("distance").notNull(), // close, 1 inch, 6 inches, etc
  
  // Technical metrics
  durationMs: integer("duration_ms").notNull(),
  peakAmplitudeDb: real("peak_amplitude_db").notNull(),
  spectralCentroid: real("spectral_centroid").notNull(), // brightness
  
  // AI Results
  advice: text("advice").notNull(),
  qualityScore: integer("quality_score").notNull(), // 0-100
  isPerfect: boolean("is_perfect").default(false),
  
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAnalysisSchema = createInsertSchema(analyses).omit({ 
  id: true, 
  createdAt: true,
  advice: true,       // Generated by backend
  qualityScore: true, // Generated by backend
  isPerfect: true     // Generated by backend
});

// Input type for the API (includes audio metrics calculated by client)
export const analysisRequestSchema = insertAnalysisSchema.extend({
  // Add any extra fields needed for the AI context but not stored if needed
});

export type Analysis = typeof analyses.$inferSelect;
export type InsertAnalysis = z.infer<typeof insertAnalysisSchema>;
